# Generated by Django 2.2.7 on 2019-11-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nick_name',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
